trigger:
  - develop

pool:
  name: 'CICD_Testing'
  demands:
    - Agent.Name -equals DESKTOP-UIPATH

steps:
- task: UiPathInstallPlatform@6
  inputs:
    cliType: 'Windows'

- task: UiPathTest@6
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath_TestConnection'
    projectKey: '9193efec-8988-0000-b111-0b49fcaa3f63'
    testProjectPath: 'project.json'
    environment: 'IniciaME'
    folderName: 'Azure_Testing'
    testReportDestination: '$(Build.ArtifactStagingDirectory)/testResult.xml'
    traceLevel: 'Verbose'

- task: UiPathPack@6
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'