trigger:
  - develop

pool:
  name: 'CICD_Testing'
  agent: 'DESKTOP-UIPATH'

steps:
# 1. Ejecutar las pruebas automatizadas del proyecto
- task: UiPathTest@6
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath_TestConnection'
    projectKey: '9193efec-8988-0000-b111-0b49fcaa3f63'
    testProjectPath: 'project.json'
    environment: 'IniciaME'
    folderName: 'Azure_Testing'
    testReportDestination: '$(Build.ArtifactStagingDirectory)/result.json'
    traceLevel: 'Verbose'

# 2. Empaquetar el proyecto de UiPath (.nupkg)
- task: UiPathPack@6
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)'

# 3. Publicar los resultados y el paquete en Azure DevOps
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'